import assert from 'node:assert/strict';
import { editorHistory, useEditorStore } from '../src/store/editorStore';
import { HISTORY_LIMIT, useEditorHistoryStore } from '../src/store/editorHistory';
import { useUIStore } from '../src/store/uiStore';
import { createSourceStoryVersion, restoreSourceStoryVersion } from '../src/lib/sourceStoryVersions';
import { sourceStoryAssemblyReadiness } from '../src/lib/sourceStoryAssembly';
import { createReleaseCandidate } from '../src/lib/releaseCandidate';
import type { ExternalMediaSource, SourceStoryAssembly } from '../src/types';

const step = async () => { await Promise.resolve(); };
const store = useEditorStore;
const ui = useUIStore;
const empty = store.getState().exportSnapshot();
const source: ExternalMediaSource = { id: 's', path: 'D:/original.mp4', name: 'original.mp4', duration: 60, size: 10, width: 1280, height: 720, createdAt: '', status: 'original', roughCutPlan: { version: 1, sourceId: 's', generatedAt: '', strategy: { pauseThreshold: 0.45, paddingBefore: 0, paddingAfter: 0, pacing: 'balanced', objective: '', thesis: '' }, candidates: [1, 10].map((start, index) => ({ id: `c${index}`, start, end: start + 3, text: 'test', decision: 'keep', boundary: 'manual', pauseBefore: null, pauseAfter: null, reason: '', visualReview: { status: 'approved', checkedAt: '', windowStart: start, windowEnd: start + 3 } })) } };
const assembly: SourceStoryAssembly = { version: 1, generatedAt: '', directorUpdatedAt: empty.director!.updatedAt, sourceSignatures: {}, items: [{ sourceId: 's', candidateId: 'c0', narrativeRole: 'hook' }, { sourceId: 's', candidateId: 'c1', narrativeRole: 'proof' }], confirmedAt: 'approved', preview: { path: 'D:/preview.mp4', duration: 6, generatedAt: '', structureFingerprint: '', boundaries: [], reviewedAt: 'approved' } };
const base = createSourceStoryVersion(assembly, [source], []);
store.getState().importSnapshot({ ...empty, sourceMedia: [source], storyAssembly: assembly, storyAssemblyVersions: [base] });
await step();
assert.equal(useEditorHistoryStore.getState().undoCount, 0);
const frozen = JSON.stringify(base);
const rc = createReleaseCandidate(store.getState().exportSnapshot());
const frozenRC = JSON.stringify(rc);

store.getState().updateDirector({ thesis: 'new thesis' }); await step();
store.getState().setStoryAssembly({ ...assembly, items: [...assembly.items].reverse(), confirmedAt: undefined, preview: undefined }); await step();
const changedSource = { ...source.roughCutPlan!, candidates: source.roughCutPlan!.candidates.map((c) => c.id === 'c0' ? { ...c, start: 1.5 } : c) };
store.getState().updateSourceMedia('s', { roughCutPlan: changedSource });
store.getState().setStoryAssembly({ ...store.getState().storyAssembly!, generatedAt: 'revised' });
await step();
assert.equal(useEditorHistoryStore.getState().undoCount, 3, 'synchronous multi-store writes group into one step');
assert(editorHistory.undo());
assert.equal(store.getState().sourceMedia[0].roughCutPlan!.candidates[0].start, 1);
assert.equal(store.getState().storyAssembly!.items[0].candidateId, 'c1');
assert.equal(store.getState().sourceMedia[0].roughCutPlan!.candidates[0].visualReview, undefined);
assert(editorHistory.undo());
assert.equal(store.getState().storyAssembly!.items[0].candidateId, 'c0');
assert(editorHistory.undo());
assert.equal(store.getState().director.thesis, empty.director!.thesis);
assert.equal(store.getState().storyAssembly!.preview, undefined);
assert.equal(store.getState().storyAssembly!.confirmedAt, undefined);
assert.equal(sourceStoryAssemblyReadiness(store.getState().storyAssembly!, store.getState().sourceMedia, store.getState().director.updatedAt).ready, false);
assert.equal(JSON.stringify(store.getState().storyAssemblyVersions[0]), frozen);
assert.equal(JSON.stringify(rc), frozenRC);
assert(editorHistory.redo()); assert(editorHistory.redo()); assert(editorHistory.redo());
assert.equal(store.getState().sourceMedia[0].roughCutPlan!.candidates[0].start, 1.5);
assert.equal(store.getState().sourceMedia[0].path, source.path);
assert.equal(store.getState().storyAssembly!.preview, undefined);

editorHistory.reset();
const prior = store.getState().sourceMedia[0].roughCutPlan!.candidates[0].start;
const restored = restoreSourceStoryVersion(base, store.getState().sourceMedia, store.getState().director);
restored.sources.forEach((s) => store.getState().updateSourceMedia(s.id, { roughCutPlan: s.roughCutPlan }));
store.getState().setStoryAssembly(restored.assembly); await step();
assert.equal(useEditorHistoryStore.getState().undoCount, 1);
editorHistory.undo(); assert.equal(store.getState().sourceMedia[0].roughCutPlan!.candidates[0].start, prior);
editorHistory.redo(); assert.equal(store.getState().sourceMedia[0].roughCutPlan!.candidates[0].start, 1);

editorHistory.reset();
const versionB = { ...base, id: 'B', label: 'B' };
store.getState().setStoryAssemblyVersions([base, versionB]); await step();
store.getState().setStoryVersionSelection({ winnerVersionId: 'B', comparedVersionIds: [base.id, 'B'], rationale: 'yes', rejectedReasons: {}, selectedAt: '' }); await step();
editorHistory.undo(); assert.equal(store.getState().storyVersionSelection, undefined);
editorHistory.undo(); assert.equal(store.getState().storyAssemblyVersions.length, 1);
editorHistory.redo(); editorHistory.redo();
assert.equal(store.getState().storyVersionSelection?.winnerVersionId, 'B');
assert.equal(JSON.stringify(store.getState().storyAssemblyVersions[1]), JSON.stringify(versionB));

editorHistory.reset();
const ids = [store.getState().addSourceClip('s', 1, 4), store.getState().addSourceClip('s', 10, 13)];
store.getState().setStoryAssembly({ ...store.getState().storyAssembly!, appliedAt: 'now', appliedBlockIds: ids }); await step();
assert.equal(useEditorHistoryStore.getState().undoCount, 1, 'assembly is atomic');
editorHistory.undo(); assert.equal(store.getState().blocks.length, 0); assert.equal(store.getState().storyAssembly!.appliedAt, undefined);
editorHistory.redo(); assert.equal(store.getState().blocks.length, 2); assert.deepEqual(store.getState().storyAssembly!.appliedBlockIds, ids);
assert.equal(store.getState().storyAssembly!.confirmedAt, undefined);

editorHistory.reset();
editorHistory.begin();
for (let i = 0; i < 4; i++) { store.getState().moveBlock(ids[0], { x: i * 10, y: 0 }); await step(); }
editorHistory.end();
assert.equal(useEditorHistoryStore.getState().undoCount, 1, 'pointer gesture is one step across animation frames');
editorHistory.undo();
store.getState().setProjectName('branch'); await step();
assert.equal(editorHistory.redo(), false, 'editing after undo discards redo branch');
const count = useEditorHistoryStore.getState().undoCount;
ui.getState().setTime(5); ui.getState().selectBlock(ids[0]); await step();
assert.equal(useEditorHistoryStore.getState().undoCount, count, 'playhead and selection are not document history');
store.getState().setProjectName('branch'); await step();
assert.equal(useEditorHistoryStore.getState().undoCount, count, 'no-op primitive writes');
editorHistory.reset();
for (let i = 0; i < HISTORY_LIMIT + 10; i++) { store.getState().setProjectName(`name${i}`); await step(); }
assert.equal(useEditorHistoryStore.getState().undoCount, HISTORY_LIMIT);
assert(!store.getState().exportProject().includes('undoCount'));
const snapshot = store.getState().exportSnapshot();
store.getState().importSnapshot(snapshot); await step();
assert.equal(editorHistory.undo(), false, 'project import starts a separate history session');
store.getState().importGeneratedSnapshot({ ...snapshot, projectName: 'generated' }); await step();
assert(editorHistory.undo(), 'generated content is undoable');
assert.equal(store.getState().projectName, snapshot.projectName);
store.getState().importSnapshot(empty);
const approvedInbox = { id: 'inbox', parentVersionId: base.id, importedAt: '', fileName: 'edl.json', input: {}, clips: [{ id: 'new', rangeIndex: 0, sourceId: 's', sourcePath: source.path, start: 1, end: 4, label: '', text: '', mappingStatus: 'confirmed' as const, boundaryStatus: 'manual' as const, boundaryConfirmed: true, visualStatus: 'approved' as const, decision: 'approve' as const, reason: '' }] };
store.getState().setExternalClipInboxes([approvedInbox]); await step();
store.setState({ storyAssemblyVersions: [base], externalClipInboxes: [{ ...approvedInbox, savedVersionId: base.id }] }); await step();
editorHistory.undo();
assert.equal(store.getState().externalClipInboxes[0].clips[0].decision, 'pending');
assert.equal(store.getState().storyAssemblyVersions.length, 0);
editorHistory.redo();
assert.equal(store.getState().externalClipInboxes[0].savedVersionId, base.id);
assert.equal(store.getState().externalClipInboxes[0].clips[0].decision, 'approve', 'saved audit evidence is immutable');
store.getState().applyVoiceTimeline(empty, { ...empty, sourceMedia: [source], storyAssembly: assembly }); await step();
assert(store.getState().undoVoiceTimeline());
assert.equal(store.getState().storyAssembly!.preview, undefined, 'legacy voice undo must also invalidate approvals');
console.log('Editor history checks passed: multi-step, atomic structure/bounds/version/assembly, drag, branching, gates, immutable evidence and import isolation.');
